# Generated by Django 3.2.6 on 2021-11-01 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Main',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='transation_id',
            new_name='transaction_id',
        ),
    ]
