# Generated by Django 3.2.6 on 2021-11-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_product_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('O', 'Out of stock'), ('N', 'New'), ('S', 'Selling Fast'), ('NA', '')], default=False, max_length=2, null=True),
        ),
    ]
